// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sficyrnogfxhbnpwbicl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmaWN5cm5vZ2Z4aGJucHdiaWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExOTQ2OTgsImV4cCI6MjA1Njc3MDY5OH0.qVtdhphaomCQRHw8WRG0jCv4alpDCKe8Z7q5nfdPbGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);